### PR TITLE
Cleanup & improvements

### PR DESCRIPTION
**Pull request by Quinten0508**
Various improvements, some cleanup and other small details. Check the commits for individual changes.

### CODE REVIEW

**Comment by Quinten0508** [comment]
As per #15, make sure to take a look at the changes made before accepting the pull request!

**Comment by Quinten0508** [comment]
Hey, you still there? 
As per **your** request I made a PR, would be cool if you could take 5 minutes out of your day to read through it and accept it!

**Comment by Quinten0508** [comment]
If you don't plan on maintaining this repo then at least make that clear - forever merging PRs isn't the solution. 
Also, I've allowed edits my maintainers so you should be able to add/remove anything you don't like.

**Comment by Quinten0508** [comment]
Right, so _you_ wanted a PR. It's been 3+ weeks and nothing but radio silence. 
Closing the PR in a week.

**Comment by maxandersen** [comment]
really sorry - completely missed these notifications.

let me go archive the project - if any one wants to fork and maintain separately please do and i'm happy to link to it.

**Pull request closed without merging**
